/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/pages/**/*.{js,ts,jsx,tsx,mdx}", "./src/components/**/*.{js,ts,jsx,tsx,mdx}", "./src/app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      screens: {
        "3xl": "1800px",
        "4xl": "2000px",
        "5xl": "2500px",
        "6xl": "3000px",
      },
      colors: {
        nightfall: "#0B0E11",
        greenGlow: "#1D8C56",
        neonGreen: "#2FF085",
        aquaGreen: "#00F29A",
        brightCyan: "#27D9FF",
        slate: "#BCC3D7",
        raven: "#010101",
        primaryGreen: "#46F245",
        darkBg: "#1E1E1E",
        emberaldBg: "#34684E",
        darkGreen: "#34684E",
        navGreen: "#1C3321",
        stroke: "#5C5C5C",
        darkText: "#B0B0B0",
        darkGrey: "#171717",
        customRed: "#FF0000",
        reddyred: "#FF5151",
        "neutral-100": "#EDEEF1",
        "neutral-200": "#D9DBE1",
        "neutral-300": "#C6C9D2",
        "neutral-400": "#8D8F95",
        "neutral-500": "#535458",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      backgroundImage: {
        "green-gradient": "linear-gradient(180deg, rgba(31, 191, 140, 0.4) 0%, rgba(17, 31, 24, 0.7) 100%)",
        "black-green-gradient": "linear-gradient(180deg, #0B0E11 0%, #1D8C56 100%)",
        subheadingGradient: "linear-gradient(180deg, #FFF 14.45%, #999 87.97%)",
        "feature-product-grid-bg": "radial-gradient(141.42% 70.71% at 50% 100%, #2FF085 7%, #0B0E11 75%)",
        "cta-gradient": "linear-gradient(90deg, #27D9FF 0%, #1D8C56 100%)",
        "insight-gradient": "linear-gradient(90deg, rgba(39, 217, 255, 0.8) 0%, rgba(17, 31, 24, 0.7) 100%)",
        "custom-gradient": "linear-gradient(251.97deg, #011F2A 0%, #018141 100%)",
        "border-color": "linear-gradient(121.53deg, rgba(40, 140, 40, 0.32) 0.75%, rgba(255, 255, 255, 0.396) 38.12%, rgba(70, 242, 69, 0.52) 99.09%)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  // plugins: [require("tailwindcss-animate")],
};
