const routes = {
  // navbar links
  home: "/",
  about: "/about", // Updated to an absolute link to the home page
  faq: "/#faq",
  services: "/services",
  programmatic: "/services/programmatic",
  measureengine: "/services/measure",
  offset: "/services/offset",
  agenticai: "/services/agentic-ai",
  howwemeasure: "/services/how-we-measure",
  resource: "/#resources",
  getStarted: "/contact",
  features: "#",
  pricing: "#",
  privacypolicy:"/privacy-policy",
  termsofuse:"/terms-of-use",
  thankpage:"/thankpage",
  AccountDeletion: "/request-for-delete",
  Calculator: "/calculator",
  // navbar buttons
  signIn: "#",
  investNow: "#",
  blog: "/blog",
  contact: "#",
  howToUse: "#",
  roadmap: "#",


   termsOfUse: "/terms-of-use",
    privacyPolicy: "/privacy-policy",
    careers: "/careers",
    blog: "/blog",
    award:"/award-nominations",
    caseStudies: "/case-studies",
    contact: "/contact-form",
    kai:"https://kai.ken42.com/",
    aboutUs: "/about-us",
    contactEmail: "/contact#email",
    contactInfo: "/contact#contact",
    contactAddress: "/contact#address",
    citiesServed: "/cities-served",
    audience: "/audience",
    servicesOffered: "/services/offered",
    servicesUseCases: "/services/use-cases",
    servicesProductDetails: "/services/product-details",
    servicesCapabilities: "/services/capabilities",
    blogStructure: "/blog/conversational-use-case-structure",
    blogReviews: "/blog/reviews",
    blogYoutubeVideos: "/blog/youtube-videos",
    blogCaseStudies: "/blog/case-studies",
    blogSocialLinks: "/blog/social-links",
    faqRealTime: "/faq/real-time",
    faqActualQuestions: "/faq/actual-questions",
    faqUnbiasedAnswers: "/faq/unbiased-answers",
    aiGallery: "/ai-gallery",
    aiGalleryFounderImages: "/ai-gallery/founder-images",
    aiGalleryEventImages: "/ai-gallery/event-images",
    aiGalleryPodcasts: "/ai-gallery/podcasts-transcriptions"
};

export default routes;
